language: rust
rust:
  - stable
  - nightly
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_script:
  - rustup component add rustfmt-preview
  - rustup component add clippy-preview

script:
  - cargo fmt --all -- --check
  - cargo clippy -- -D warnings
  - cargo build --all
  - cargo test --all-features