env: dev
namespace: dinopark-dev
assume_role: arn:aws:iam::320464205386:role/dino-park-fossil-role-dev-us-west-2
settings:
  auth: https://dev.mozilla-dev.auth0.com/
  avatar__s3_bucket: cis-avatars-dev
  avatar__picture_api_url: https://picture.api.dev.sso.allizom.org
